Development
Mesi21/Tic-Tac-Toe pull request #1
Opened 2019-05-08 15:58 UTC by Mesi21

2019-05-09 01:48 UTC, rvvergara requested changes
Hi @Mesi21 and @codermlw,

Please note that as it is you haven't followed the required directory structure for your project. Per instructions in Pathwright:

![image](https://user-images.githubusercontent.com/6015315/57421358-07729780-723e-11e9-9dcc-11bd93957985.png)

Also you packed all your code inside `main.rb`. Please ensure you split your code into the right directory structure and observe proper architecture:

1 file each for each of your classes (I assume you will have Board, Game and Player classes)
1 file for any user interface related module (or depending on the type of module, one file per module)
1 main.rb file whose content is very simple (initializing the necessary classes and running the main method of the game class).

Some pointers to help you build this game the OOP way:

1. You need to first decide which classes to have. In my experience building at least 2 versions of this game both in Ruby and JavaScript (vanilla and React versions) what you would normally need will be 3 classes - `Game`, `Board` and `Player` classes.

2. Think about what **single responsibility** each class will have. Please take note of the word **single**. For instance, I would suppose the `Game` class is responsible for ensuring the each player will alternately take turns until the game is over (game is over whenever one of the players has won or if there are no more squares in the board to choose from). Now in order for the game class to accomplish this what methods does it need to have? What data does it need to hold? Quick answer to the second question - it needs to have player1 and player2 and also the board (to check for winners and if it's all filled up). Consequently you will know how to build your Player and Board classes based on this. 

3. Don't ever mix your User Interface logic with your classes. OOP principles are there to ensure your objects/classes are reusable and not tightly coupled with other objects. Only the necessary methods a class needs should reside in it (meaning logic for it to perform its sole responsibility). Your UI Logic can be placed in its own module which your classes will only include (for instance if the Player class needs to get user input then the Player class will simply include the UI module to be able to use that method of asking a user's input).

There, that's a lot for initial review and clarification on what you need to do. I suggest you first work on the classes.

2019-05-09 01:48 UTC, rvvergara commented on README.md
> +_Made in Ruby_
Made with Ruby, or better yet you can say "Created using Ruby"

2019-05-09 01:48 UTC, rvvergara commented on main.rb
> +    attr_accessor :symbol, :name, :moves
Why do we need `:symbol, :name and :moves` to be in `attr_accessor` ? Do we need to reassign their values later on? By placing them as writeable attributes (which `attr_accessor` makes them) you are making other objects/classes able to reassign their values. Is that what we want to accomplish?

2019-05-09 01:48 UTC, rvvergara commented on main.rb
> +    def display_board
This method mixes UI logic into your class. Please separate this into a UI module that this class will just include. Please see my main comment on guidance on how to build your classes.

2019-05-09 01:48 UTC, rvvergara commented on main.rb
> +    def play
Like the one before it, this is UI related logic and shouldn't be in here

2019-05-09 01:48 UTC, rvvergara commented on main.rb
> +    def move(player)
Again, this method mixes UI related logic

2019-05-09 01:48 UTC, rvvergara commented on main.rb
> +puts "======================================="
There's a lot of work we need to do guys. Please see my main comment on how to properly build this app.

2019-05-11 01:44 UTC, rvvergara requested changes
Hi @Mesi21 and @codermlw,

Great job splitting your code into the right directories! That in itself is already a huge step forward. Now, what we need to do is to work on the classes to make your code truly OOP. Please see my comments in each code piece.

2019-05-11 01:44 UTC, rvvergara commented on bin/main.rb
> +require_relative "../lib/player"
We will tackle this file later on once we are agreeable on your classes. So for now I will focus my attention to your three classes

2019-05-11 01:44 UTC, rvvergara commented on lib/board.rb
> +    def display_board
One of the first things we need to understand is that our classes shouldn't be entangled with UI. To build the Board class properly let's answer the ff questions:

1. What should the Board be doing (it's single responsibility, nothing more, nothing less)? 
2. When we get to answer this question the next question will be - in order for the Board to accomplish that single responsibility what data should it be holding (or what instance variables should it have)? And also, what methods will allow the Board to do its job? 
3. When we determine the attributes/instance variables needed by the Board, then we need to know which of these variables do we want to be exposed publicly (`attr_reader`). The same goes for the methods; which methods do we want to be callable by other objects (public methods) vs the methods that only our Board class knows about (private methods).

From these questions you will be able to build this class more properly.

2019-05-11 01:44 UTC, rvvergara commented on lib/game.rb
> +    def line?
What does this method do?

2019-05-11 01:44 UTC, rvvergara commented on lib/game.rb
> +         puts "#{@turns % 2 == 1 ? "#{@player_2.name}" : "#{@player_1.name}"} won!"
This is UI related code and shouldn't reside inside the Classes

2019-05-11 01:44 UTC, rvvergara commented on lib/player.rb
> +    attr_accessor :moves
Do we need to make this publicly writeable? Why did we put this in `attr_accessor`?

2019-05-11 01:44 UTC, rvvergara commented on lib/player.rb
> +    def initialize(name, symbol)
Good job with this initialize method!

 Now what your Player class lacks (see my comment on the Board class for guidance on how to build classes properly) is/are the appropriate method/s it needs to perform its responsibility. Answer the first question then, what does the Player class needs to be doing?

2019-05-11 01:44 UTC, rvvergara commented on lib/game.rb
> +class Game
Please see my comment on the Board class to help you build this Game class. You are already in the right direction. And let's work on this step by step.

For the Game class I'd like to give you some points to start with - The Game class is the object that controls the flow of the game. Meaning its job is to ensure player1 and player2 alternately takes turns until the game is finished (i.e., one of them has won or there are no more spaces in the board to play).

2019-05-15 13:39 UTC, rvvergara requested changes
It's my first time to see the game in action. It looks so good and works great too! I could play and either player could win (or have a tie).

However, we still need to make sure the code is robust and truly OOP :) so pls see my comments below. The Game class still needs a lot of overhaul as it is.. Player class just needs to have one method (and if you hit the mark it will be perfect!). Board is somehow ok, we'll see later on if we can stil improve it (upon implementing the changes we need in the Player and Game classes).

2019-05-15 13:39 UTC, rvvergara commented on lib/player.rb
> +    include UserInterface
Let's give Player a turn/move method here that takes in user the user input (coming from the UI which your module takes care of) and updates its moves array and also updates the board. So it means we also need to include the board as an input to this method.

Please note I didn't say you should put the code that requests user input here. The move/turn method should be something like:

```
def method(user's choice, board)
  do something with that user's choice by updating moves and board
end
```

2019-05-15 13:39 UTC, rvvergara commented on lib/board.rb
> +    def fill_pos(pos, symbol)
This can be that method that the player's turn/move method calls when updating the board (see my comment on Player.rb).

2019-05-15 13:39 UTC, rvvergara commented on lib/board.rb
> +    def is_valid?(index)
This sanitization of user's input should happen in the `UI module` move method. What that method will pass into the player's turn/move method (see my comment on player.rb) will already be sanitized.

2019-05-15 13:39 UTC, rvvergara commented on lib/game.rb
> +      puts "Winner is: #{over?}"
We still are including UI related code here.

2019-05-15 13:39 UTC, rvvergara commented on lib/game.rb
> +      puts 'It is a tie'
Still a UI related code

2019-05-15 13:39 UTC, rvvergara commented on lib/game.rb
> +      valid_move = player.move(@game_board)
See my comment on player.rb in relation to this

2019-05-15 13:39 UTC, rvvergara commented on lib/game.rb
> +  def over?
For this method, can't we further simplify it? A game is over IF 1) One of the players has won (so we can have a method that checks if either player1 has won or player2 has won) OR 2) There are no more empty space in the board ( you already have a board method that checks if it's already full). So this method can simply return `true` or `false` depending on that condition. Let's simplify it, we don't need the lines that has @player1.name or @player2.name here

2019-05-15 13:39 UTC, rvvergara commented on lib/game.rb
> +  def win?
Can't we use simple `each` method here? So it's easier to understand.. You already have the game winning combination (array of arrays) so we can easily compare this to a player's moves array and find out if the player has won (if his moves array contains any of the internal arrays in `lines`)

2019-05-16 09:36 UTC, Mesi21 commented on lib/game.rb
> +  def win?
Hi. We are not understanding your comments exactly. Would it be possible to schedule a call to talk about these changes that you are asking from us? Your feedback would help us a lot.

2019-05-22 01:35 UTC, rvvergara approved these changes
HI @Mesi21 and @codermlw/ @i4seeu, 

Great job! You guys are very diligent. Ok I am giving you a 

# :+1: 

but I have a recommendation in the `Game` class that might help you in the next project (which is writing tests for this program).

You may now merge into `master` and submit a completion form. :)

2019-05-22 01:35 UTC, rvvergara commented on lib/player.rb
> +    def update(choice,board)
Great!

2019-05-22 01:35 UTC, rvvergara commented on lib/board.rb
> +    def win?(moves)
Nice! Although for styling purposes please put spaces between your methods

2019-05-22 01:35 UTC, rvvergara commented on lib/game.rb
> +  def cycle
For now this particular version of `cycle` will do. But I highly recommend you guys to further simplify this. Make it shorter so that later on, the succeeding project, when you write specs for it it will be easier for you guys.

2019-05-22 09:19 UTC, merged